#!/bin/bash

# W wybranym katalogu projektu muszą znajdować się poniższe katalogi (lub przynajmniej jeden z nich):
# /tests/
# /functional_tests/

projectslist="[ANULUJ] $(for i in ~/Projects/*; do [ -d "$i" ] && echo $i | sed 's!.*/!!' ; done)"
PS3='Wybierz projekt: ' # Komunikat opisujący listę opcji
printf "%b" "\a\n\nLista dostępnych projektów:\n" >&2
select project in $projectslist; do
    # $REPLY, instrukcja select zwraca ciąg tekstowy opcji
    if [ "$project" = "anuluj" ]; then 
        break
    elif [ -n "$project" ]; then 
        project_dir="$HOME/Projects/$project"        
        test_command=""
        if [ -f $project_dir/manage.py ]; then
            test_command="python $project_dir/manage.py test" 
        else
            return 1
        fi

        functional_tests_dir=$(find $project_dir -type d -name "functional_tests" | sed 's/\s/\n/g')
        unit_tests_dir=$(find $project_dir -maxdepth 2 -type d -name "tests" -not -path "$project_dir/*static/*")
        
        if [ -n "$functional_tests_dir" ] && [ -n "$unit_tests_dir" ]; then
            testslist="[ANULUJ] wszystkie_testy testy_funkcjonalne klasa_testów_funkcjonalnych pojedynczy_test_funkcjonalny testy_jednostkowe klasa_testów_jednostkowych pojedynczy_test_jednostkowy"
            ps3='wybierz zestaw testów do wykonania: ' # komunikat opisujący listę opcji
            printf "%b" "\a\nlista dostępnych testów:\n" >&2
            select test_set in $testslist; do
                case $REPLY in
                    1) break;;
                    2) $($test_command $project_dir); break;; # echo "wybrano wszystkie_testy ";;
                    3) $($test_command $functional_tests_dir); break;; #dla pojedynczego katalogu!
                    4) echo "klasa testów funkcjonalnych";;
                    5) echo "pojedynczy test funkcjonalny";;
                    6) for tests in $unit_tests_dir; do
                           $($test_command $tests);
                       done 
                       break;;
                    7) echo "klasa testów jednostkowych";;
                    8) echo "pojedynczy test jednostkowy";;
                    *) echo "Nie ma takiej opcji!"
                esac
            done
        fi
        break 
    else           
        echo "nie ma takiego projektu!"       
        break
    fi # koniec analizy odpowiedzi użytkownika    
done # koniec procedury wyboru projektu
